version: '3'

services:
  php:
    build: ./.docker/php
    volumes:
      - ./src:/app
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./src:/app
      - ./logs/nginx:/var/log/nginx/
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "1234:80"
  mysql:
    image: mysql:5.7
    ports:
      - "1235:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db
  pma:
    image: phpmyadmin/phpmyadmin:edge-4.8
    ports:
      - "1236:80"
    environment:
      - PMA_HOST=mysql
